services:
  production-health-api:
    image: aditya0910/production-health-api:latest
    container_name: production-health-api

    ports:
      - "5000:5000"

    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./logs:/app/logs
      - ./data:/app/data